version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: pos_postgres
    environment:
      POSTGRES_DB: pos_system
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: